use std::collections::HashMap;

#[derive(Default)]
pub struct GreedyTokenizer {
    trie: Vec<Node>,
    rev: std::collections::HashMap<u32, Vec<u8>>, // reverse map for decode/tests
}

#[derive(Default)]
struct Node {
    next: HashMap<u8, usize>,
    id: Option<u32>,
}

impl GreedyTokenizer {
    pub fn from_cl100k_bin() -> Self {
        let entries = load_cl100k_bin_entries();
        Self::from_entries(entries)
    }

    pub fn from_entries(entries: Vec<(Vec<u8>, u32)>) -> Self {
        let mut trie = Vec::new();
        trie.push(Node::default());
        let mut rev = std::collections::HashMap::new();
        for (bytes, id) in entries {
            let mut node = 0usize;
            for &b in &bytes {
                let next = if let Some(&nx) = trie[node].next.get(&b) {
                    nx
                } else {
                    let nx = trie.len();
                    trie.push(Node::default());
                    trie[node].next.insert(b, nx);
                    nx
                };
                node = next;
            }
            trie[node].id = Some(id);
            rev.insert(id, bytes);
        }
        GreedyTokenizer { trie, rev }
    }

    pub fn encode(&self, text: &str) -> Vec<u32> {
        let bytes = text.as_bytes();
        let mut out = Vec::new();
        let mut i = 0usize;
        while i < bytes.len() {
            let mut node = 0usize;
            let mut best = None;
            let mut best_end = i;
            let mut j = i;
            while j < bytes.len() {
                let b = bytes[j];
                if let Some(&nx) = self.trie[node].next.get(&b) {
                    node = nx;
                    if let Some(id) = self.trie[node].id {
                        best = Some(id);
                        best_end = j + 1;
                    }
                    j += 1;
                } else {
                    break;
                }
            }
            if let Some(id) = best {
                out.push(id);
                i = best_end;
            } else {
                out.push(bytes[i] as u32);
                i += 1;
            }
        }
        out
    }

    pub fn decode(&self, tokens: &[u32]) -> Vec<u8> {
        let mut out = Vec::new();
        for &t in tokens {
            if let Some(b) = self.rev.get(&t) {
                out.extend_from_slice(b);
            } else if t <= 255 {
                // byte fallback
                out.push(t as u8);
            }
        }
        out
    }

    // Fast path: count tokens without allocating the output vector.
    pub fn count_tokens(&self, text: &str) -> usize {
        let bytes = text.as_bytes();
        let mut count = 0usize;
        let mut i = 0usize;
        while i < bytes.len() {
            let mut node = 0usize;
            let mut best = None;
            let mut best_end = i;
            let mut j = i;
            while j < bytes.len() {
                let b = bytes[j];
                if let Some(&nx) = self.trie[node].next.get(&b) {
                    node = nx;
                    if let Some(id) = self.trie[node].id {
                        best = Some(id);
                        best_end = j + 1;
                    }
                    j += 1;
                } else {
                    break;
                }
            }
            if best.is_some() {
                count += 1;
                i = best_end;
            } else {
                count += 1;
                i += 1;
            }
        }
        count
    }
}

// Note: Header parsing path removed; we use only pre-converted binary.

fn load_cl100k_bin_entries() -> Vec<(Vec<u8>, u32)> {
    // Generated by scripts/convert_cl100k_to_bin.cpp
    const BIN: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/data/cl100k_base.bin"));
    let mut i = 0usize;
    let read_u32 = |i: &mut usize| -> u32 {
        let v = (BIN[*i] as u32)
            | ((BIN[*i + 1] as u32) << 8)
            | ((BIN[*i + 2] as u32) << 16)
            | ((BIN[*i + 3] as u32) << 24);
        *i += 4;
        v
    };
    let read_u16 = |i: &mut usize| -> u16 {
        let v = (BIN[*i] as u16) | ((BIN[*i + 1] as u16) << 8);
        *i += 2;
        v
    };

    if BIN.len() < 12 {
        return Vec::new();
    }
    let magic = read_u32(&mut i);
    let _version = read_u32(&mut i);
    let count = read_u32(&mut i) as usize;
    if magic != 0x50414D54 {
        return Vec::new();
    } // 'TMAP'

    let mut out = Vec::with_capacity(count);
    for _ in 0..count {
        if i + 6 > BIN.len() {
            break;
        }
        let id = read_u32(&mut i);
        let len = read_u16(&mut i) as usize;
        if i + len > BIN.len() {
            break;
        }
        let bytes = BIN[i..i + len].to_vec();
        i += len;
        out.push((bytes, id));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ascii_punct_first_ids() {
        let tm = GreedyTokenizer::from_cl100k_bin();
        // From header preview: '!'->0, '"'->1, '#'=>2, '$'=>3, '%'=>4, '\''->6, '('->7, ')'=>8
        let cases: Vec<(char, u32)> = vec![
            ('!', 0),
            ('"', 1),
            ('#', 2),
            ('$', 3),
            ('%', 4),
            ('\'', 6),
            ('(', 7),
            (')', 8),
        ];
        for (ch, expected) in cases {
            let s = ch.to_string();
            let ids = tm.encode(&s);
            assert_eq!(ids, vec![expected], "char {:?}", ch);
        }
    }

    #[test]
    fn phrase_token_tail_example() {
        let tm = GreedyTokenizer::from_cl100k_bin();
        // From header tail: "IENvbnZleW9y" -> " Conveyor" -> 100255
        let s = " Conveyor";
        let ids = tm.encode(s);
        assert_eq!(ids, vec![100255]);
        let bytes = tm.decode(&ids);
        assert_eq!(bytes, s.as_bytes());
    }
}
