#!/usr/bin/env python3
"""
Convert cl100k_base_data.h to Rust-friendly assets for the nvs-tokenmonster crate.

This script reads the header's byte array, decodes to ASCII mapping lines
("<base64> <id>" per line), and writes a compact text file the Rust crate can
embed, plus a tiny Rust module wrapper that includes that text.

Outputs (relative to repo root):
  - rust/crates/nvs-tokenmonster/data/cl100k_base.txt
  - rust/crates/nvs-tokenmonster/src/cl100k_data.rs

Note: The tokenizer crate can also parse the header directly without running
this script; this is provided for convenience/repeatability.
"""
from __future__ import annotations
import os
import re
import sys


def extract_bytes_from_header(header_path: str) -> bytes:
    with open(header_path, 'rb') as f:
        content = f.read().decode('latin1')
    m = re.search(r"cl100k_base_tiktoken\[\]\s*=\s*\{(.*?)\}\s*;", content, re.S)
    if not m:
        raise RuntimeError("Could not find cl100k_base_tiktoken array in header")
    body = m.group(1)
    hex_bytes = re.findall(r"0x([0-9a-fA-F]{2})", body)
    return bytes(int(h, 16) for h in hex_bytes)


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def main() -> None:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    header_default = os.path.join(repo_root, 'integration-work', 'fast-pdf-parser', 'include', 'fast_pdf_parser', 'cl100k_base_data.h')
    header_path = sys.argv[1] if len(sys.argv) > 1 else header_default

    if not os.path.exists(header_path):
        print(f"Header not found: {header_path}", file=sys.stderr)
        sys.exit(1)

    raw = extract_bytes_from_header(header_path)
    text = raw.decode('utf-8', errors='replace')

    crate_root = os.path.join(repo_root, 'rust', 'crates', 'nvs-tokenmonster')
    data_dir = os.path.join(crate_root, 'data')
    src_dir = os.path.join(crate_root, 'src')
    ensure_dir(data_dir)
    ensure_dir(src_dir)

    data_txt = os.path.join(data_dir, 'cl100k_base.txt')
    with open(data_txt, 'w', encoding='utf-8') as f:
        f.write(text)

    rs_module = os.path.join(src_dir, 'cl100k_data.rs')
    with open(rs_module, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scripts/convert_cl100k_to_rust.py\n')
        f.write('// Contains a reference to the decoded CL100K mapping lines.\n')
        f.write('pub const CL100K_BASE: &str = include_str!("../data/cl100k_base.txt");\n')

    print("Wrote:")
    print(f"  - {data_txt}")
    print(f"  - {rs_module}")


if __name__ == '__main__':
    main()

