[workspace]
members = [
    "crates/nvs-format",
    "crates/nvs-core",
    "crates/nvs-packer",
    "crates/tokenmonster",
    "crates/nvs-pdf",
    "crates/nvs-pdf-core",
    "crates/nvs-html-core",
    "crates/nvs-html",
    "crates/nvs-embed",
    "crates/nvs-cli",
    "crates/nvs",
    "crates/nvs-lambda-sample",
    "crates/tiny-search-engine",
    "crates/devcheck",
]

resolver = "2"
