name: Build and Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (build but do not publish)'
        required: false
        default: 'true'

jobs:
  build-prebuilds:
    uses: ./.github/workflows/prebuilds.yml

  publish:
    needs: build-prebuilds
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Download all prebuilds
        uses: actions/download-artifact@v4
        with:
          pattern: prebuilds-*
          merge-multiple: true
          path: prebuilds/
      
      - name: List all prebuilds
        run: |
          echo "Downloaded prebuilds:"
          find prebuilds -name "*.node" -type f | sort
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Create package
        run: |
          # Ensure prebuilds are in the right location
          echo "Package contents:"
          npm pack --dry-run
      
      - name: Publish to npm (if not dry run)
        if: github.event_name == 'release' || github.event.inputs.dry_run != 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Upload package artifact
        if: github.event.inputs.dry_run == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: "*.tgz"