name: C/C++ CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libomp-dev libsimdjson-dev
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: configure
      run: ./configure
      
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck